package com.softdesign.devintensive.data.storage.entities;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REPOSITORIES".
*/
public class DbRepositoryDao extends AbstractDao<DbRepository, Long> {

    public static final String TABLENAME = "REPOSITORIES";

    /**
     * Properties of entity DbRepository.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RemoteId = new Property(1, String.class, "remoteId", false, "REMOTE_ID");
        public final static Property UserRemoteId = new Property(2, String.class, "userRemoteId", false, "USER_REMOTE_ID");
        public final static Property GitUrl = new Property(3, String.class, "gitUrl", false, "GIT_URL");
    };

    private DaoSession daoSession;

    private Query<DbRepository> dbUser_MRepositoriesQuery;

    public DbRepositoryDao(DaoConfig config) {
        super(config);
    }
    
    public DbRepositoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REPOSITORIES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REMOTE_ID\" TEXT NOT NULL UNIQUE ," + // 1: remoteId
                "\"USER_REMOTE_ID\" TEXT," + // 2: userRemoteId
                "\"GIT_URL\" TEXT);"); // 3: gitUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REPOSITORIES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbRepository entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRemoteId());
 
        String userRemoteId = entity.getUserRemoteId();
        if (userRemoteId != null) {
            stmt.bindString(3, userRemoteId);
        }
 
        String gitUrl = entity.getGitUrl();
        if (gitUrl != null) {
            stmt.bindString(4, gitUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbRepository entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRemoteId());
 
        String userRemoteId = entity.getUserRemoteId();
        if (userRemoteId != null) {
            stmt.bindString(3, userRemoteId);
        }
 
        String gitUrl = entity.getGitUrl();
        if (gitUrl != null) {
            stmt.bindString(4, gitUrl);
        }
    }

    @Override
    protected final void attachEntity(DbRepository entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbRepository readEntity(Cursor cursor, int offset) {
        DbRepository entity = new DbRepository( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // remoteId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userRemoteId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // gitUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbRepository entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRemoteId(cursor.getString(offset + 1));
        entity.setUserRemoteId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGitUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbRepository entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbRepository entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "mRepositories" to-many relationship of DbUser. */
    public List<DbRepository> _queryDbUser_MRepositories(String userRemoteId) {
        synchronized (this) {
            if (dbUser_MRepositoriesQuery == null) {
                QueryBuilder<DbRepository> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserRemoteId.eq(null));
                dbUser_MRepositoriesQuery = queryBuilder.build();
            }
        }
        Query<DbRepository> query = dbUser_MRepositoriesQuery.forCurrentThread();
        query.setParameter(0, userRemoteId);
        return query.list();
    }

}
